<?php $marques= [
    "Électronique"=>[
        "Apple",
        "Samsung",
        "LG",
        "Microsoft",
        "HP",
        "Dell",
        "Canon",
        "Nikon",
        "Bose"
    ],
    "Mode et vêtements"=>[
        "Nike",
        "Adidas",
        "Zara",
        "H&M",
        "Gucci",
        "Louis Vuitton",
        "Chanel",
        "Levi's",
        "Gap",
        "Tommy Hilfiger"
    ],
    "Maison et jardin"=>[
        "IKEA",
        "West Elm",
        "Pottery Barn",
        "Home Depot",
        "Lowe's",
        "Wayfair",
        "Williams-Sonoma",
        "Target",
        "Amazon Basics",
        "Crate & Barrel"
    ],
    "Beauté et soins personnels"=>[
        "L'Oréal",
        "Maybelline",
        "MAC",
        "Estée Lauder",
        "Clinique",
        "Nivea",
        "Dove",
        "Revion",
        "Olay",
        "Neutogena"
    ],
    "Jouets et jeux"=>[
        "Lego",
        "Hasbro",
        "Mattel",
        "Fisher-Price",
        "Nerf",
        "Playmobil",
        "Ravensburger",
        "Barbie",
        "Hot Wheels",
        "Mellisa & Doug"
    ],
    "Sports et loisirs"=>[
        "Nike",
        "Adidas",
        "Puma",
        "Under Armour",
        "Reebook",
        "Columbia",
        "The North Face",
        "Decathlon",
        "Wilson",
        "Garmin"
    ],
    "Livres et médias"=>[
        "Penguin Random House",
        "HarperCollins",
        "Hachette Livre",
        "Simon & Schuster",
        "National Geographic",
        "Disney",
        "Marvel Comics",
        "Warner Bros",
        "Spotify",
        "Netflix"
    ],
    "Automobile et accessoires"=>[
        "Toyota",
        "Volkswagen",
        "Ford",
        "BMW",
        "Mercedes-Benz",
        "Honda",
        "Chevrolet",
        "Michelin",
        "Bosch",
        "Thule"
    ],
    "Alimentation et boissons"=>[
        "Coca-Cola",
        "Nestlé",
        "McDonald's",
        "Kellogg's",
        "Danone",
        "PepsiCo",
        "Mars",
        "Unilever",
        "Starbucks",
        "Heinz"
    ],
    "Santé et bien-être"=>[
        "Johnson & Johnson",
        "Pfizer",
        "GSK(GlasonSmithKline)",
        "Procter & Gamble",
        "Fitbit",
        "L'Oréal",
        "AstraZeneca",
        "Abbot Laboratories",
        "Himalaya Herbals",
        "YogaGlo"
    ],
    "Bijoux et montres"=>[
        "Tiffany & Co",
        "Cartier",
        "Swarovski",
        "Rolex",
        "Pandora",
        "Chopard",
        "Michael Kors",
        "Bulgari",
        "Pandora",
        "Fossil"
    ],
    "Art et artisanat"=>[
        "Winsor & Newton",
        "Faber-Castell",
        "Etsy",
        "Hobby Lobby",
        "Canson",
        "Crayola",
        "Moleskine",
        "Blick Art Materials",
        "Martha Stewart Crafts",
        "Derwent"
    ],
    "Équipement informatique"=>[
        "Apple",
        "Dell",
        "HP",
        "Lenovo",
        "Asus",
        "Microsoft",
        "Acer",
        "Intel",
        "Logitech",
        "Samsung"
    ],
    "Musique et instruments"=>[
        "Yamaha",
        "Fender",
        "Gibson",
        "Roland",
        "Steinway & Sons",
        "Shure",
        "Pioneer DJ",
        "Native Instruments",
        "Marshall",
        "Ernie Ball"
    ],
    "Bébés et enfants"=>[
        "Pampers",
        "Fisher-Price",
        "Gerber",
        "LEGO",
        "Graco",
        "Johnson & Johnson",
        "Chicco",
        "Huggies",
        "Skip Hop",
        "VTech"
    ]
];